# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
    ]
